### PR TITLE
Let's Team UP

### PR DESCRIPTION
**Pull request by cabusao10**
I'm creating Godswar Private Server using your initial codes. So far I managed to enter the MAP
I am done with:
1.  Login Module
2. Create and Delete Characters

I also fixed your sockets.

### CODE REVIEW

**Comment by AxDSan** [comment]
> I'm creating Godswar Private Server using your initial codes. So far I managed to enter the MAP
> I am done with:
> 
> 1. Login Module
> 2. Create and Delete Characters
> 
> I also fixed your sockets.

Fine, you submit your changes for review and approval.

**Comment by cabusao10** [comment]
> > I'm creating Godswar Private Server using your initial codes. So far I managed to enter the MAP
> > I am done with:
> > 
> > 1. Login Module
> > 2. Create and Delete Characters
> > 
> > I also fixed your sockets.
> 
> Fine, you submit your changes for review and approval.

Hey there, sorry for late reply, are you still interested to team up with this project? I would like to make this project private, you can email at cabusaorhen14@gmail.com or if you have Facebook account you can visit my page and PM there. www.facebook.com/GodsWarPrivateServer

**Comment by AxDSan** [comment]
Yes but now that IGG pulled the plug on GodsWar this project is now useless, unless some Chinese people had a private server already up and running we can continue 🤷‍♂️

**Comment by onyxaqua2000** [comment]
so this project is useless now?

**Comment by AxDSan** [comment]
Pretty much, unless someone had an unreleased, private server fully
completed… other than that, this project is totally useless.. can be used
for research/study purposes.

**Pull request merged**
